# Generated by Django 6.1 on 2026-09-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider')], default='patient', max_length=20)),
                ('title', models.CharField(blank=True, help_text='e.g. Clinical Psychologist, Psychiatrist, Marriage & Family Therapist', max_length=100)),
                ('specialization', models.CharField(blank=True, choices=[('Anxiety & Stress', 'Anxiety & Stress'), ('Relationships', 'Relationships'), ('Depression', 'Depression'), ('Trauma Recovery', 'Trauma Recovery'), ('General', 'General')], help_text='Provider specialization area', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
