# Generated by Django 6.1 on 2026-09-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_update_alert_status_choices'),
        ('journals', '0002_journalentry_confidence_journalentry_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='journals.journalentry'),
        ),
    ]
