# Generated by Django 6.1 on 2026-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='counseling_type',
            field=models.CharField(choices=[('in_person', 'In-Person Session')], default='in_person', max_length=20),
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
