# Generated by Django 6.1 on 2026-09-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_counseling_type_and_more'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
            ],
            options={
                'verbose_name': 'Availability slot',
                'verbose_name_plural': 'Availability slots',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.availability',),
        ),
    ]
