# Generated by Django 6.1 on 2026-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
