"""
Crisis and Concern Configuration for MindMirror AI.
This module defines vetted risk patterns, category keywords, and crisis response resources.
Keep this configuration easily editable and auditable.
"""

# Crisis-tier expressions indicating urgent safety concerns or acute self-harm intent
# Based on vetted crisis hotline identification benchmarks
CRISIS_KEYWORDS_AND_PHRASES = [
    "want to die",
    "kill myself",
    "killing myself",
    "end my life",
    "ending my life",
    "commit suicide",
    "suicidal",
    "suicide",
    "better off dead",
    "don't want to live",
    "no reason to live",
    "hurt myself",
    "hurting myself",
    "self harm",
    "self-harm",
    "hang myself",
    "take all my pills",
    "overdose",
    "slit my wrists",
    "can't go on living",
    "goodbye forever",
    "no way out",
]

# Non-crisis concern category keywords mapped directly to provider SPECIALIZATIONS
# Generic valence words (hate, sad, angry, upset, mad) are excluded so category matching
# is driven strictly by subject matter and distress topics.
CONCERN_CATEGORY_KEYWORDS = {
    "Anxiety & Stress": [
        "stress",
        "stressed",
        "stressful",
        "stressing",
        "anxious",
        "anxiety",
        "panic",
        "panic attack",
        "overthinking",
        "racing thoughts",
        "can't relax",
        "cannot relax",
        "nervous about",
        "nervous",
        "nervousness",
        "deadline",
        "exam stress",
        "overwhelmed",
        "overwhelming",
        "insomnia",
        "chest tight",
        "constant worry",
        "worry",
        "worried",
        "worrying",
        "can't cope",
        "cannot cope",
        "pressure",
        "restless",
        "restlessness",
        "burnout",
        "burnt out",
        "on edge",
        "dread",
        "dreading",
        "hyperventilating",
        "heart racing",
    ],
    "Relationships": [
        "partner",
        "partners",
        "boyfriend",
        "boyfriends",
        "girlfriend",
        "girlfriends",
        "spouse",
        "spouses",
        "husband",
        "husbands",
        "wife",
        "wives",
        "relationship",
        "relationships",
        "marriage",
        "marriages",
        "dating",
        "breakup",
        "breakups",
        "break up",
        "broke up",
        "broken up",
        "divorce",
        "divorced",
        "divorcing",
        "cheated",
        "cheating",
        "infidelity",
        "marital",
        "toxic relationship",
        "heartbroken",
        "fiancé",
        "fiance",
        "fiancee",
        "ex-husband",
        "ex-wife",
        "ex-partner",
        "in-laws",
        "mother-in-law",
        "father-in-law",
    ],
    "Depression": [
        "depressed",
        "depression",
        "hopeless",
        "hopelessness",
        "empty",
        "emptiness",
        "numb",
        "numbness",
        "no motivation",
        "unmotivated",
        "worthless",
        "worthlessness",
        "can't get out of bed",
        "cannot get out of bed",
        "lost interest",
        "crying all day",
        "crying every day",
        "giving up on everything",
        "giving up",
        "anhedonia",
        "pointless",
        "sadness",
        "despair",
        "dark thoughts",
        "miserable",
        "misery",
        "feeling down",
        "down in the dumps",
        "gloomy",
        "heavy heart",
        "no purpose",
    ],
    "Trauma Recovery": [
        "flashback",
        "flashbacks",
        "nightmare",
        "nightmares",
        "trigger",
        "triggers",
        "triggered",
        "triggering",
        "abuse",
        "abusive",
        "abused",
        "assault",
        "assaulted",
        "assaulting",
        "accident",
        "accidents",
        "can't stop thinking about what happened",
        "cannot stop thinking about what happened",
        "ptsd",
        "reliving the past",
        "past keeps coming back",
        "traumatic",
        "trauma",
        "attacked",
        "victim",
        "harassment",
        "harassed",
        "domestic violence",
    ],
}

# Threshold parameters for trend-based detection
CONSECUTIVE_NEGATIVE_THRESHOLD = 3
NEGATIVE_CONFIDENCE_THRESHOLD = 70.0

# 24/7 Verified Emergency Crisis Resources
CRISIS_RESOURCES = [
    {
        "name": "988 Suicide & Crisis Lifeline",
        "coverage": "United States & Canada",
        "phone": "988",
        "sms": "988",
        "url": "https://988lifeline.org",
        "description": "Free, confidential 24/7 support available by call or text.",
    },
    {
        "name": "Crisis Text Line",
        "coverage": "US, UK, Canada, Ireland",
        "phone": None,
        "sms": "741741",
        "text_keyword": "HOME",
        "url": "https://www.crisistextline.org",
        "description": "Text HOME to 741741 to connect with a crisis counselor 24/7.",
    },
    {
        "name": "The Trevor Project (LGBTQ Youth)",
        "coverage": "United States",
        "phone": "1-866-488-7386",
        "sms": "678-678",
        "text_keyword": "START",
        "url": "https://www.thetrevorproject.org",
        "description": "24/7 confidential suicide prevention and crisis intervention.",
    },
    {
        "name": "Find A Helpline (International)",
        "coverage": "Worldwide (Global Directory)",
        "phone": None,
        "sms": None,
        "url": "https://findahelpline.com",
        "description": "Free, confidential crisis lines in over 130 countries.",
    },
    {
        "name": "Befrienders Worldwide",
        "coverage": "International Network",
        "phone": None,
        "sms": None,
        "url": "https://www.befrienders.org",
        "description": "Emotional support to prevent suicide worldwide.",
    },
]
