# Generated by Django 6.1 on 2026-09-10 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('audio', 'Audio'), ('exercise', 'Exercise')], max_length=20)),
                ('url', models.URLField(help_text='Direct link to external content (YouTube, article, audio, etc.)')),
                ('category', models.CharField(choices=[('Anxiety & Stress', 'Anxiety & Stress'), ('Relationships', 'Relationships'), ('Depression', 'Depression'), ('Trauma Recovery', 'Trauma Recovery'), ('General', 'General')], help_text='Category corresponding to wellness/specialization area', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
